---
title: "Discussion 10"
output: html_document
---
#### 1.	Perform a Scenario Design analysis as described below.  Consider whether it makes sense for your selected recommender system to perform scenario design twice, once for the organization (e.g. Amazon.com) and once for the organization's customers. 

The website that I chose to use for my example is the safari books online catalogue. It is a paid subscription service,  but they recommend books for you to check out based on your recent activity (books you have read) and topics of interest that they have selected for you.

Who are the target users? 
	- The target users are those who pay for the safari books subscription.

What are their key goals?
	- The goal of those users is to read books, do research, and learn about various topics of interest as they relate to the technology and business world.

How can you help them accomplish those goals? 
	- In order to help users learn, Safari curates learning paths, and provides access to thousands of  books that can be read online through their website, without having to purchase those individual books or training paths.

#### 2.	Attempt to reverse engineer what you can about the site, from the site interface and any available information that you can find on the Internet or elsewhere. 

There is a clear indication of how the site works to provide those recommendations. There is a "recommended" section on the page, which shows the books they think you would be interested in. They clearly state that topics you set, and recent activity are used to make those recommendations.  Each  book you select to read has a predefined topic or keywords associated with it, and my guess is that content-based filtering is used to make those recommendations, but they might also use collaborative filtering as well.

#### 3.	Include specific recommendations about how to improve the site's recommendation capabilities going forward.  
My recommendation is that O'Reilly/Safari use something more than content based filtering. The recommendations are not very good ones, because the topics for each software are general or too broad. I think a combination of making more topics and using a different recommendation engine, either in addition to or in place of their current one, to get a more specific recommendation for the user.
